name: tables-detr
channels:
 - conda-forge
 - pytorch
 - defaults
dependencies:
  - python=3.6.10
  - pip
  - pytorch==1.5.0
  - cudatoolkit==10.1.243
  - jupyter
  - ipykernel
  - torchvision==0.6.0
  - pandas==0.25.3
  - opencv==4.1.2
  - scikit-learn==0.21.3
  - tqdm==4.39.0
  - itkwidgets==0.23.1 
  - cython
  - numpy==1.17 
  - pip:
    - scikit-image
    - git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI
    - tensorboard==2.0.1
    - tensorboardx==1.9
    - scipy==1.1.0
    - jupytext==1.3.0
    - PyMuPDF==1.16.14
